apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: account-frontend${SERVICE_SUFFIX}
  annotations:
    serving.knative.dev/route: account-frontend${SERVICE_SUFFIX}
    run.googleapis.com/ingress: ${INGRESS}
  labels:
    service-name: account-frontend

spec:
  template:
    metadata:
      name: account-frontend${SERVICE_SUFFIX}${REVISION_SUFFIX}
      annotations:
        autoscaling.knative.dev/maxScale: '${MAX_SCALE}'
        autoscaling.knative.dev/minScale: '${MIN_SCALE}'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/vpc-access-connector: projects/${GCP_PROJECT}/locations/${GCP_REGION}/connectors/um-cloud
        run.googleapis.com/vpc-access-egress: private-ranges-only
      labels:
        service-name: account-frontend
    spec:
      containerConcurrency: 512
      timeoutSeconds: 300
      serviceAccountName: account@${GCP_PROJECT}.iam.gserviceaccount.com
      containers:
        - name: stardust-account-frontend
          image: ${IMAGE_URL}
          ports:
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
